Fix compilation error of Windows targets
General\General.cs(70,58): error CS0234: The type or namespace name 'Form' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)